return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  -- { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
  -- { "plugin", enaabled = false},
}
